[package]
name = "sound_effights_research"
version = "0.1.0"
authors = ["Simon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.8"
pitch-detection = "0.1.0"

[lib]
crate-type = ["cdylib"]